### ISSUE TITLE
Preparation of the first published version

### ISSUE THREAD

**Issue by jchiquet** [computorg/published-202204-deeplearning-occupancy-lynx#3]
In order to prepare the final version, we need a DOI. To this end, I need affiliations for all the authors. 

```yaml
descrition: |
  Short description of this paper
author:
  - name: Olivier Gimenez
    url: https://oliviergimenez.github.io/
    affiliation: UMR 5175 CEFE
    affiliation-url: https://www.cefe.cnrs.fr/
  - name: Maëlis Kervellec
    url: 
    affiliation: 
    affiliation-url: 
  - name: Jean-Baptiste Fanjul
    url: 
    affiliation:
    affiliation-url: 
  - name: Anna Chaine
    url: 
    affiliation:
    affiliation-url: 
  - name: Lucile Marescot
    url: 
    affiliation:
    affiliation-url: 
  - name: Yoann Bollet
    url: 
    affiliation:
    affiliation-url: 
  - name: Christophe Duchamp
    url: 
    affiliation:
    affiliation-url: 
```
Then a final proofreading must be done by the authors. Final modifications should be made via pull-request.

**Comment by oliviergimenez** [comment]
Good morning @jchiquet. Affiliations are given below. I've deleted the url field for some of the co-authors. We'll get to the proofreading asap.

```
descrition: |
  Short description of this paper
author:
  - name: Olivier Gimenez
    url: https://oliviergimenez.github.io/
    affiliation: CEFE, Univ Montpellier, CNRS, EPHE, IRD, Montpellier, France
    affiliation-url: https://www.cefe.cnrs.fr/
  - name: Maëlis Kervellec
    affiliation: CEFE, Univ Montpellier, CNRS, EPHE, IRD, Montpellier, France
    affiliation-url: https://www.cefe.cnrs.fr/
  - name: Jean-Baptiste Fanjul
    affiliation: Fédérations Départementales des Chasseurs du Jura, Arlay, France
    affiliation-url: https://www.chasseurdujura.com/
  - name: Anna Chaine
    affiliation: CEFE, Univ Montpellier, CNRS, EPHE, IRD, Montpellier, France
    affiliation-url: https://www.cefe.cnrs.fr/
  - name: Lucile Marescot
    affiliation: CBGP, Univ Montpellier, CIRAD, INRAE, Institut Agro, IRD, Montpellier, France
    affiliation-url: https://www6.montpellier.inrae.fr/cbgp
  - name: Yoann Bollet
    affiliation: Fédération Départementale des Chasseurs de l'Ain, Bourg-en-Bresse, France
    affiliation-url: http://www.fdcain.com/
  - name: Christophe Duchamp
    affiliation: Office Français de la Biodiversité, Unité Espèces à enjeux, Gap, France
    affiliation-url: https://www.ofb.gouv.fr/
```
